### PR TITLE
Fix android samsung

### PR DESCRIPTION
**Pull request by pgiraud**
With this pull request the fix with OpenLayers button clicks not being taken into account on some devices (including Samsung S5 to S7 and Nexus 10 running Android 5).

OpenLayers has been upgraded so that this commit is in. https://github.com/openlayers/ol2/commit/a7e628397dd3199a99b852de16c777f8c001

For an unknown reason though, the application doesn't behave correctly, and it doesn't seem related to the OpenLayers upgrade. I had to change the "painted" event listener to "show" for the main view in order to get the map rendered. Also some views (settings or background layers) don't show up correctly until we try to scroll them.

@jaykayone Are you able to test this pull request in your environment and see what happens?

### CODE REVIEW

**Comment by jaykayone** [comment]
Hi @pgiraud, I don't think my dev environment is still running. Could you provide an apk that we could test?

**Comment by pgiraud** [comment]
It looks like Sencha touch doesn't support recent versions of Chrome due to a deprecation.
http://trevorbrindle.com/chrome-43-broke-sencha/

I added the proposed patch in the application. Now the application behaves correctly on view show and the OL controls respond to click.

Please review.

**Comment by pgiraud** [comment]
The last commit helps fixing issues with longpress not being correctly taken into account on recent Android devices using recent version of Chrome.
Recent commits into OL2 have fixed wrong touch event management.

**Comment by pgiraud** [comment]
This has been tested and validated. Merging.

**Pull request merged**
